---
- name: Ensure the key is present
  apt_key:
    url: http://nginx.org/keys/nginx_signing.key
- name: Add repository
  apt_repository:
    repo: 'deb http://nginx.org/packages/debian/ wheezy nginx'
    state: present
  notify:
  - Update apt
- name: Ensure nginx is at the latest version
  apt:
    pkg: nginx
    state: latest
- name: Ensure the log archive folder is here
  file:
    path: /var/log/nginx/archive
    state: directory
- name: Rotate logs and archive
  lineinfile:
    dest: /etc/logrotate.d/nginx
    state: present
    line: '        olddir /var/log/nginx/archive'
    insertafter: '        sharedscripts'
- name: Writes the secured version of the configuration
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    backup: yes
  notify:
  - Restart nginx
- name: Ensure nginx is running
  service: 
    name: nginx
    state: started
    enabled: yes

