---
- name: Ensure the key is present
  shell: apt-key adv --keyserver keyserver.ubuntu.com --recv 7F0CEB10
- name: Add repository
  apt_repository:
    repo: 'deb http://downloads-distro.mongodb.org/repo/debian-sysvinit dist 10gen'
    state: present
  notify:
  - update apt
- name: Ensure mariadb is installed
  apt:
    pkg: mongodb-10gen
    state: latest
