---
- name: Ensure hhvm GPG key is present
  shell: wget -O - http://dl.hhvm.com/conf/hhvm.gpg.key | apt-key add -
- name: Add repository
  apt_repository:
    repo: 'deb http://dl.hhvm.com/debian wheezy main'
    state: present
  notify:
  - update apt
- name: Install HHVM
  apt: 
    name: hhvm
    state: latest
