---
- name: Ensure hhvm GPG key is present
  apt_key:
    url: http://dl.hhvm.com/conf/hhvm.gpg.key
- name: Add repository
  apt_repository:
    repo: 'deb http://dl.hhvm.com/debian wheezy main'
    state: present
  notify:
  - Update apt
- name: Install HHVM
  apt: 
    name: hhvm
    state: latest
- name: Ensure the /var/www folder is here
  file:
    path: /var/www
    state: directory
- name: Install Supervisor conf for HHVM
  copy:
    src: hhvm.conf
    dest: /etc/supervisor/conf.d/hhvm.conf
    backup: yes
  notify:
  - Reread supervisor conf