---
- name: ensure supervisor is at the latest version
  apt:
    pkg: supervisor
    state: latest
- name: remove supervisor lock
  file: 
    path: /run/supervisord.lock
    state: absent
- name: Ensure specific supervisor conf is here
  file:
    path: /etc/supervisor/conf.d
    state: directory
- name: ensure supervisor is running
  service: 
    name: supervisor
    state: started