---
- name: ensure node is installed
  apt:
    pkg: "{{item}}"
    state: latest
  with_items:
   - nodejs
   - nodejs-legacy
   - sqlite # required for node / ghost generally
- name: Get NPM
  shell: curl https://npmjs.org/install.sh | sudo sh
