---
- name: Ensure node is installed
  apt:
    pkg: "{{item}}"
    state: latest
  with_items:
   - nodejs
   - nodejs-legacy
   - sqlite # required for node / ghost generally
- name: Check if NPM is here
  command: "which npm || echo '0'"
  register: npm_is_here
  ignore_errors: True
- name: Install NPM
  shell: curl -L -k https://npmjs.org/install.sh | sudo sh
  when: npm_is_here.stdout == 0
