---
- name: Update apt
  apt: update_cache=yes
- name: Upgrade apt
  apt: upgrade=full
- name: Ensure sudo is installed
  apt:
    pkg: sudo
    state: latest
- name: Add correct /etc/apt/sources.list file
  copy:
    src: sources.list
    dest: "/etc/apt/sources.list"
    owner: root
- name: "Add user to sudo group"
  user:
    name: "{{user}}"
    append: yes
    groups: sudo
    createhome: no
- name: "Make user sudo with no-password"
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^{{user}} ALL="
    line: "{{user}} ALL=(ALL) NOPASSWD:ALL"
    validate: 'visudo -cf %s'
    create: True
- name: Install base packages
  apt:
    pkg: "{{ item }}"
    state: installed
  with_items:
    - unzip
    - tar
    - make
    - curl
    - vim
    - wget
    - rsync
    - cron
    - gcc
    - python-mysqldb # Needed to interact with mysql
- name: Ensure rookie packages are not here
  apt:
    pkg: "{{ item }}"
    state: absent
  with_items:
   - apache2
   - php