---
- name: Ensure ruby and YUI are installed
  apt:
    pkg: "{{item}}"
    state: latest
  with_items:
   - ruby
   - ruby-dev
   - yui-compressor
- name: Ensure SASS / COMPASS / LESS are here
  sudo: yes
  gem:
    name: "{{item}}"
    state: latest
    user_install: yes
  with_items:
   - sass
   - compass
   - less
