---
- name: Update apt
  apt:
    update_cache: yes
- name: Reread supervisor conf
  supervisorctl:
    name: hhvm
    state: present
- name: Restart nginx
  service:
    name: nginx
    state: restarted
    enabled: yes